version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/react-text-balancer" # 패키지별 package.json
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/ssr-testing"
    schedule:
      interval: "weekly"
