name: "Install"
description: "Sets up Node.js and runs install"

inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: "package.json"
        cache: "pnpm"
        registry-url: https://npm.pkg.github.com/
        scope: "@goorm-dev"
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Install Dependencies
      shell: bash
      run: pnpm i --frozen-lockfile
