name: "[CD] Release"

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - name: Install
        uses: ./.github/composite-actions/install
        with:
          github-token: ${{ secrets.DEPLOYMENT_TOKEN }}

      - name: Create .npmrc file
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
