name: Security Audit
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *" # 매일 UTC 자정 실행
  workflow_dispatch: # 수동 실행 옵션 추가
jobs:
  security_audit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Run security audit
        id: audit
        run: |
          pnpm audit --audit-level=high --prod --json > audit-report.json
          echo "result=$(jq -r '.metadata.vulnerabilities | to_entries[] | "\(.key)=\(.value)"' audit-report.json)" >> $GITHUB_OUTPUT

      - name: Critical vulnerability check
        if: steps.audit.outputs.result != ''
        uses: actions/github-script@v7
        with:
          script: |
            const { result } = process.env
            if (result.includes('critical') || result.includes('high')) {
              core.setFailed('Critical/High severity vulnerabilities detected')
            }

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-report
          path: audit-report.json
